### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [astleychen/status-bot#4]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by astleychen** [comment]
@dtolnay Thanks for the notification. All I need is simply a function to decode JSON data into a struct. I've made the change and replace rustc_serialize to serde now.
1a99e3ca4a71898dc8411bd7a85cbbfc40e311da

**Comment by astleychen** [comment]
Tested and the issue is fixed now.
